name: Build Container Pipeline
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: | 
          java --version
          mvn --version
          #What did this action create for us?
          cat /home/runner/.m2/settings.xml
          
      - name: Build with Maven
        run: | 
          cat settings.xml
